#!/usr/bin/env sh

################################################################################
# When on a branch referring to a Jira issue,
# ensure commit messages start with the issue reference

# Allow skipping
case ${SKIP:-} in *prepare-commit-msg*) exit 0 ;; esac

# Don't alter fixup messages
grep -q "^fixup! " "$1" && exit 0

JIRA_CODE_PATTERN=${JIRA_CODE_PATTERN:-$(git config --get mr.jira-code-pattern)}
if [ -z "$JIRA_CODE_PATTERN" ]; then
    echo "JIRA_CODE_PATTERN not set - unable to guess issue code" >&2
    exit 0
fi

current_branch=$(git rev-parse --abbrev-ref HEAD)
issue_code=$(echo "${current_branch}" | grep -Eo "$JIRA_CODE_PATTERN" | tail -n1)
[ -n "$issue_code" ] || exit 0 # No issue code detected

current_msg=$(cat "$1")
msg_code=$(echo "${current_msg}" | grep -iEo "$JIRA_CODE_PATTERN" | tail -n1)
[ -z "$msg_code" ] || exit 0 # existing issue code in message

echo "Prefixing message with issue code: $issue_code" >&2
sed -i.bak -e "1s/^/$issue_code /" "$1"
