name: Tests

on: [push, pull_request]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.8.2

      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Test
        run: bats ./test
