name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'completion/**'
      - 'doc/**'
      - 'git-mr-completion.bash'
      - 'LICENSE'
      - 'README.md'
  push:
    branches:
      - master
    paths-ignore:
      - 'completion/**'
      - 'doc/**'
      - 'git-mr-completion.bash'
      - 'LICENSE'
      - 'README.md'

jobs:

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        run: |
          sudo apt-get update -y
          sudo apt-get install shellcheck
          LC_ALL=C.UTF-8 shellcheck git-mr

  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04
          - windows-2025
          - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - name: Show versions
        run: |
          bash --version
          git --version

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.12.0

      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run tests on ${{ matrix.os }}
        run: bash -c "bats --print-output-on-failure --formatter tap ./test"

  test-mac:
    name: Test (Mac)
    strategy:
      matrix:
        os:
           - macos-15
           - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: |
          brew install \
            bash \
            gnu-sed \
            grep

      - name: Show versions
        run: |
          bash --version
          git --version

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.12.0

      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run tests on ${{ matrix.os }}
        run: bash -c "bats --print-output-on-failure --formatter tap ./test"
